### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mattybme** [derekdanderson/createdraftarticlefromcase#2] opened 2021-09-07 15:35 UTC
It says the repository could not be found when I try and login to a prod instance

**Comment by derekdanderson** [comment] 2021-09-07 21:04
Should be fixed now.  Try again.

**Comment by derekdanderson** [comment] 2021-09-07 21:17
This issue was caused by moving away from the branch name "master" and moving to "main".  I updated the deploy link to account for this.

**Closed as completed by derekdanderson** 2021-09-07 21:17 UTC
Labels: bug

**Comment by mattybme** [comment] 2021-09-09 13:52
Thanks @derekdanderson it installs now! :)
